version: '3'
services:
  python-server:
    image: python:3.8
    volumes:
      - .:/app
    working_dir: /app
    command: python3 -m http.server
    ports:
      - 8000:8000

  node-server:
    image: node:14
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 3000:3000
    command: bash -c "npm install && node server.js"